#!/usr/bin/env node
// =============================================================================
// packages/cli/scripts/prepack.mjs
//
// Purpose
// -------
// Copy the persona library and skill files from the REPO ROOT into the CLI
// package directory, so that `npm pack` / `npm publish` produces a tarball
// containing them. Runs automatically via the `prepare` npm script.
//
// The single source of truth in this repo is at the REPO ROOT:
//
//     <repo-root>/assets/personas/      <-- canonical persona library
//     <repo-root>/skills/               <-- Claude Code skills
//     <repo-root>/.agents/skills/       <-- Codex CLI skills
//
// Everything inside `packages/cli/{assets,skills,.agents}/` is an EPHEMERAL
// MIRROR generated by this script. It is gitignored and MUST NOT be edited
// directly. Edit the canonical copies at the repo root instead — the next
// time `prepare` runs (on `npm install`, `npm pack`, or `npm publish`), the
// mirror is recreated from scratch.
//
// Why this exists
// ---------------
// npm's `files` field can only ship paths inside the package dir. To bundle
// personas + skills into the npm tarball, they must physically live at
// `packages/cli/{assets,skills,.agents}/` at publish time. Committing the
// duplicates to git would put two copies of the same content in the repo;
// this script is the replacement — copies happen at pack time and never get
// committed.
//
// Master-vs-public filtering
// --------------------------
// Master ships skills the public mirror does NOT (e.g. `release-public`,
// which is internal release tooling). If this script blindly copied every
// skill, `npm publish` from master would ship master-only skills to end
// users. To prevent that, this script reads
// `<repo-root>/scripts/build-public.allowlist.json` when it exists and
// uses its `copies` field as the allowlist. In the public clone the
// allowlist doesn't ship (it's denied), so the script falls back to
// "copy everything found" — which is identical because the public clone
// only contains the public surface area anyway.
//
// When this runs
// --------------
//   npm install           (inside the workspace)                  -> yes (prepare)
//   npm pack              (inside packages/cli/)                  -> yes
//   npm publish           (inside packages/cli/)                  -> yes
//   Just running the CLI  (no install/pack)                       -> no, not needed
//                                                                    (CLI walks up to
//                                                                     <repo-root>/assets/personas)
//
// Rules for humans and agents
// ---------------------------
//   1. NEVER edit files under packages/cli/{assets,skills,.agents}/.
//      They are gitignored and will be overwritten on the next `npm install`.
//   2. ALWAYS edit canonical copies at the repo root.
//   3. To ADD a new skill or persona category that should reach the public:
//      a) Drop it at the repo root (skills/<name>/ or assets/personas/<cat>/).
//      b) Add its path to `scripts/build-public.allowlist.json` (`copies`).
//      c) The next `npm install` re-runs prepack and picks it up.
//   4. To ADD a master-only skill or private persona category:
//      a) Drop it at the repo root.
//      b) DO NOT add it to `scripts/build-public.allowlist.json`.
//      c) It stays in master, never reaches the public mirror or the npm
//         tarball.
//   5. To verify what would ship in the next publish:
//         cd packages/cli && npm pack --dry-run
// =============================================================================

import { cpSync, existsSync, mkdirSync, readFileSync, readdirSync, rmSync, statSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url));
const PKG_ROOT = resolve(SCRIPT_DIR, "..");            // packages/cli/
const REPO_ROOT = resolve(PKG_ROOT, "..", "..");       // repo root

/**
 * Try to load the build-public allowlist. Present in master, absent in the
 * public clone. Returns the Set of allowlisted source paths, or null if
 * the file isn't there (signaling "copy everything").
 */
function loadPublicAllowlist() {
  const path = join(REPO_ROOT, "scripts/build-public.allowlist.json");
  if (!existsSync(path)) return null;
  try {
    const data = JSON.parse(readFileSync(path, "utf-8"));
    return new Set(data.copies ?? []);
  } catch (e) {
    console.warn(`prepack: WARN — could not parse allowlist (${e.message}); falling back to copy-all`);
    return null;
  }
}

function normalize(p) {
  return p.replace(/\\/g, "/").replace(/\/+$/, "");
}

function copyDir(src, dest) {
  if (existsSync(dest)) rmSync(dest, { recursive: true, force: true });
  mkdirSync(dirname(dest), { recursive: true });
  cpSync(src, dest, { recursive: true });
}

const allowlist = loadPublicAllowlist();
const mode = allowlist === null ? "copy-all (public clone — no allowlist found)" : "allowlist-filtered (master)";
console.log(`prepack: mode = ${mode}`);

// Personas: copy the entire assets/personas/ tree. The repo-root view already
// reflects the master-vs-public split — any category that's private to master
// lives only on disk in master and is filtered out by the public build script
// before the public clone is ever created. So we don't need per-category
// filtering here.
{
  const srcRel = "assets/personas";
  const src = join(REPO_ROOT, srcRel);
  const dest = join(PKG_ROOT, srcRel);
  if (existsSync(src)) {
    copyDir(src, dest);
    console.log(`prepack: ${srcRel}  →  packages/cli/${srcRel}`);
  } else {
    console.warn(`prepack: WARN — missing source ${src}`);
  }
}

// Skills (Claude + Codex): enumerate each subdir individually and apply the
// allowlist when present.
for (const skillsRel of ["skills", ".agents/skills"]) {
  const src = join(REPO_ROOT, skillsRel);
  if (!existsSync(src) || !statSync(src).isDirectory()) {
    console.warn(`prepack: WARN — missing source ${src}`);
    continue;
  }
  // Wipe the destination first so removed/renamed skills don't linger.
  const destBase = join(PKG_ROOT, skillsRel);
  if (existsSync(destBase)) rmSync(destBase, { recursive: true, force: true });

  for (const entry of readdirSync(src, { withFileTypes: true })) {
    if (!entry.isDirectory()) continue;
    const childRel = `${skillsRel}/${entry.name}`;
    if (allowlist !== null && !allowlist.has(normalize(childRel))) {
      console.log(`prepack: skip ${childRel} (master-only, not in public allowlist)`);
      continue;
    }
    const childSrc = join(src, entry.name);
    const childDest = join(destBase, entry.name);
    copyDir(childSrc, childDest);
    console.log(`prepack: ${childRel}  →  packages/cli/${childRel}`);
  }
}
